#1971  cd devika/
#1972  git status
#1973  ollama ls 
#1974  ollama serve
#1975  ls
#1976  cd ..
#1977  ls
#1978  ls -ltra 
#1979  source .venv/bin/activate
#1980  ollama serve
#1981  docker ps 
#1982  docker images 
#1983  sudo bash 
#1984  cd devika/
#1985  ls
#1986  sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
#1987  nvidia-container-cli -k -d /dev/tty info
#1988  nvidia-smi 
#1989  nvidia-container-cli 
#1990  sudo apt-get purge nvidia-*
#1991  sudo apt-get update
#1992  sudo apt-get autoremove
#1993  ubuntu-drivers devices
#1994  apt search nvidia-driver
#1995  sudo apt install libnvidia-common-550 libnvidia-gl-550  nvidia-driver-550
#1996  reboot 
#1997  sudo reboot 
#1998  ls
#1999  sudo apt install -y nvidia-docker2
#2000  sudo systemctl daemon-reload
#2001* sudo systemctl restart docke
#2002  sudo systemctl daemon-reload
#2003  sudo systemctl restart docker
#2004  dpkg -l | grep docker
#2005  snap list docker 
#2006  snap list 
#2007  snap list | grep -i docker
#2008  snap list | grep -ie docker
#2009  snap list 
#2010  docker --version 
#2011  dpkg -l | grep docker
#2012  apt-cache search nvidia-docker
#2013  apt search nvidia-docker
#2014  snap remove docker
#2015  sudo snap remove docker
#2016  apt-get remove docker.io
#2017  sudo apt-get remove docker.io
#2018  sudo apt-get install docker-ce
#2019  docker ps 
#2020  docker --version 
#2021  $ sudo service docker restart
#2022  sudo apt update
#2023  sudo apt install -y nvidia-docker2
#2024  sudo service docker start
#2025  sudo apt install -y nvidia-docker2
#2026  docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
#2027  curl -s -L nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
#2028  distribution=$(. /etc/os-release; echo $ID$VERSION_ID)
#2029  curl -s -L nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
#2030  sudo apt-get update
#2031  sudo apt install -y nvidia-docker2
#2032  sudo service docker restart
#2033  nvidia-smi 
#2034  docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
#2035  history 
#

version: "3.9"
# sudo apt install libnvidia-common-550 libnvidia-gl-550 nvidia-driver-550
services:
  ollama-service:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - 11434:11434
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/ || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
